version: "3"

# Services
services:
  # MySQL Service
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - inception

  #WORDPRESS
  wordpress:
    depends_on:
       - mariadb
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file: .env
    image: wordpress
    networks:
      - inception
    restart: always
  #NGINX WEBSERVER
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: 
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    volumes:
      - wordpress-data:/var/www/wordpress

#Volumes
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rrajaobe/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rrajaobe/data/wordpress

#Networks
networks:
  inception: 